project:
  type: website
  output-dir: docs

website:
  title: "Introdução ao Git & GitHub"
  navbar:
    left:
      - href: index.qmd
        text: Início


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



